/**
 * Covers the deterministic image generation route contract:
 *
 *   - POST /api/groups/:jid/generate-image persists generated bytes under
 *     generated-images/ in the workspace folder and stores a path-based
 *     attachment (no inline base64) on the message row.
 *   - POST with references forwards them to the service layer.
 *   - GET /api/groups/:jid/generated-images returns the lightweight gallery
 *     listing (path references + legacy inline rows).
 *   - Non-web workspaces and disabled workspaces are rejected.
 */
import fs from 'fs';
import os from 'os';
import path from 'path';
import sharp from 'sharp';

import {
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  test,
  vi,
} from 'vitest';

const SHARED_TMP =
  process.env.HAPPYCLAW_TEST_DATA_DIR ??
  (() => {
    const d = fs.mkdtempSync(
      path.join(os.tmpdir(), 'happyclaw-routes-generate-image-'),
    );
    process.env.HAPPYCLAW_TEST_DATA_DIR = d;
    return d;
  })();

vi.mock('../src/config.js', async (importOriginal) => {
  const real = (await importOriginal()) as Record<string, unknown>;
  const dataDir = process.env.HAPPYCLAW_TEST_DATA_DIR!;
  return {
    ...real,
    DATA_DIR: dataDir,
    GROUPS_DIR: path.join(dataDir, 'groups'),
    STORE_DIR: path.join(dataDir, 'db'),
  };
});

vi.mock('../src/logger.js', () => ({
  logger: { debug: () => {}, info: () => {}, warn: () => {}, error: () => {} },
}));

vi.mock('../src/middleware/auth.ts', () => ({
  authMiddleware: async (c: any, next: any) => {
    c.set('user', {
      id: process.env.HAPPYCLAW_TEST_USER_ID ?? 'alice',
      username: 'alice',
      role: process.env.HAPPYCLAW_TEST_USER_ROLE ?? 'member',
      status: 'active',
      permissions: [],
    });
    return next();
  },
}));

vi.mock('../src/web.js', () => ({
  broadcastNewMessage: () => {},
  invalidateAllowedUserCache: () => {},
}));

const generateWorkspaceImage = vi.fn();
vi.mock('../src/image-generation-service.js', async (importOriginal) => {
  // Only `generateWorkspaceImage` needs mocking (no real network calls in
  // route tests); the size-resolution constants/helper are pure and kept
  // real so the route's zod schema and size lookups behave identically to
  // production.
  const actual =
    await importOriginal<typeof import('../src/image-generation-service.js')>();
  return {
    ...actual,
    generateWorkspaceImage: (...args: unknown[]) =>
      generateWorkspaceImage(...args),
    ImageGenerationError: class ImageGenerationError extends Error {
      constructor(
        message: string,
        readonly status: 400 | 409 | 502 | 504,
      ) {
        super(message);
      }
    },
  };
});

const groupRoutesModule = await import('../src/routes/groups.js');
const fileRoutesModule = await import('../src/routes/files.js');
const db = await import('../src/db.js');
const webContext = await import('../src/web-context.js');

const groupRoutes = groupRoutesModule.default;
const fileRoutes = fileRoutesModule.default;

const OWNER_ID = 'alice';
const JID = 'web:image-group';
const FOLDER = 'image-group';
const TINY_PNG = Buffer.from([
  0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00,
]);

beforeAll(() => {
  fs.mkdirSync(path.join(SHARED_TMP, 'db'), { recursive: true });
  fs.mkdirSync(path.join(SHARED_TMP, 'groups'), { recursive: true });
  db.initDatabase();
  webContext.setWebDeps({
    getRegisteredGroups: () => ({}),
  } as unknown as Parameters<typeof webContext.setWebDeps>[0]);
});

afterEach(() => {
  generateWorkspaceImage.mockReset();
  delete process.env.HAPPYCLAW_TEST_USER_ID;
  delete process.env.HAPPYCLAW_TEST_USER_ROLE;
});

function seedGroup(jid = JID, folder = FOLDER): void {
  db.setRegisteredGroup(jid, {
    name: 'Image Group',
    folder,
    added_at: new Date().toISOString(),
    executionMode: 'container',
    created_by: OWNER_ID,
    conversation_source: 'web',
  } as Parameters<typeof db.setRegisteredGroup>[1]);
}

function seedImageEnabled(): void {
  // Direct binding row so the config exists without the full profile flow.
  db.setWorkspaceImageGenerationConfig(FOLDER, true, 'gpt-image-2');
  const binding = db.getWorkspaceAgentProfileBinding(FOLDER);
  expect(binding).toBeDefined();
}

describe('POST /:jid/generate-image', () => {
  beforeEach(() => {
    seedGroup();
    db.getOrCreateDefaultAgentProfile(OWNER_ID);
    db.assignWorkspaceAgentProfile(
      FOLDER,
      db.getOrCreateDefaultAgentProfile(OWNER_ID).id,
    );
    seedImageEnabled();
    generateWorkspaceImage.mockResolvedValue({
      data: TINY_PNG.toString('base64'),
      mimeType: 'image/png',
    });
  });

  test('persists the image as a workspace file and references it by path', async () => {
    const res = await groupRoutes.request(`/${JID}/generate-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt: 'a hedgehog' }),
    });
    expect(res.status).toBe(200);
    const body = (await res.json()) as { image: { path: string } };
    expect(body.image.path).toMatch(/^generated-images\/generated-.*\.png$/);

    const absolute = path.join(SHARED_TMP, 'groups', FOLDER, body.image.path);
    expect(fs.existsSync(absolute)).toBe(true);
    expect(fs.readFileSync(absolute).subarray(0, 4)).toEqual(
      TINY_PNG.subarray(0, 4),
    );

    // Message attachment references the path — no inline base64 payload.
    const imageRow = db
      .getMessagesPage(JID, undefined, 10)
      .find((m) => m.sender === '__image_generation__');
    expect(imageRow).toBeDefined();
    const attachments = JSON.parse(imageRow!.attachments as string);
    expect(attachments[0].type).toBe('image');
    expect(attachments[0].path).toBe(body.image.path);
    expect(attachments[0].data).toBeUndefined();
    // No references were sent, so the recipe carries only the prompt plus
    // the (default) quality/aspectRatio used for this generation.
    expect(attachments[0].recipe).toEqual({
      prompt: 'a hedgehog',
      quality: '4k',
      aspectRatio: '4:3',
    });
  });

  test('persists reference images and attaches a reusable recipe', async () => {
    const res = await groupRoutes.request(`/${JID}/generate-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt: 'merge the scenes',
        references: [
          {
            data: TINY_PNG.toString('base64'),
            mimeType: 'image/png',
            note: '角色造型',
          },
          { data: TINY_PNG.toString('base64'), mimeType: 'image/png' },
        ],
      }),
    });
    expect(res.status).toBe(200);

    const imageRow = db
      .getMessagesPage(JID, undefined, 10)
      .find((m) => m.sender === '__image_generation__');
    const attachments = JSON.parse(imageRow!.attachments as string);
    const recipe = attachments[0].recipe as {
      prompt: string;
      references: Array<{ path: string; mimeType: string; note?: string }>;
    };
    // The recipe keeps the original (un-composed) prompt, separate from the
    // per-reference notes, so "reuse recipe" restores clean editable inputs.
    expect(recipe.prompt).toBe('merge the scenes');
    expect(recipe.references).toHaveLength(2);
    expect(recipe.references[0].note).toBe('角色造型');
    expect(recipe.references[1].note).toBeUndefined();
    for (const ref of recipe.references) {
      expect(ref.path).toMatch(/^generated-images\/ref-.*\.png$/);
      const absolute = path.join(SHARED_TMP, 'groups', FOLDER, ref.path);
      expect(fs.existsSync(absolute)).toBe(true);
    }
  });

  test('forwards references to the service and composes per-image notes into the prompt', async () => {
    const res = await groupRoutes.request(`/${JID}/generate-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt: 'merge the scenes',
        references: [
          {
            data: TINY_PNG.toString('base64'),
            mimeType: 'image/png',
            note: '角色造型',
          },
          { data: TINY_PNG.toString('base64'), mimeType: 'image/png' },
        ],
      }),
    });
    expect(res.status).toBe(200);
    expect(generateWorkspaceImage).toHaveBeenCalledTimes(1);
    const [prompt, model, refs] = generateWorkspaceImage.mock.calls[0];
    // The service prompt also carries an explicit quality/aspect-ratio
    // directive (default 4K / 4:3 here) — `size` alone doesn't reliably
    // steer every upstream model.
    expect(prompt).toBe(
      'merge the scenes\n\n参考图 1：角色造型\n\n请生成画质为 4K 高清、画面比例为 4:3（横版）的图片。',
    );
    expect(model).toBe('gpt-image-2');
    expect(refs).toHaveLength(2);
    expect(Buffer.from(refs[0].data)).toEqual(TINY_PNG);
    expect(refs[0].mimeType).toBe('image/png');
    expect(refs[1].note).toBeUndefined();
  });

  test('defaults to 4K / 4:3 when quality and aspectRatio are omitted', async () => {
    const res = await groupRoutes.request(`/${JID}/generate-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt: 'a hedgehog' }),
    });
    expect(res.status).toBe(200);
    const [, , , size] = generateWorkspaceImage.mock.calls[0];
    expect(size).toBe('3328x2496');

    const imageRow = db
      .getMessagesPage(JID, undefined, 10)
      .find((m) => m.sender === '__image_generation__');
    const attachments = JSON.parse(imageRow!.attachments as string);
    expect(attachments[0].recipe.quality).toBe('4k');
    expect(attachments[0].recipe.aspectRatio).toBe('4:3');
  });

  test('threads a custom quality/aspectRatio through to the size and the recipe', async () => {
    const res = await groupRoutes.request(`/${JID}/generate-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt: 'a hedgehog',
        quality: '2k',
        aspectRatio: '16:9',
      }),
    });
    expect(res.status).toBe(200);
    const [, , , size] = generateWorkspaceImage.mock.calls[0];
    expect(size).toBe('1920x1080');

    const imageRow = db
      .getMessagesPage(JID, undefined, 10)
      .find((m) => m.sender === '__image_generation__');
    const attachments = JSON.parse(imageRow!.attachments as string);
    expect(attachments[0].recipe.quality).toBe('2k');
    expect(attachments[0].recipe.aspectRatio).toBe('16:9');
  });

  test('rejects an invalid aspectRatio', async () => {
    const res = await groupRoutes.request(`/${JID}/generate-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt: 'a hedgehog', aspectRatio: '5:4' }),
    });
    expect(res.status).toBe(400);
  });

  test('rejects a non-web workspace', async () => {
    seedGroup('feishu:image-group', 'image-group-feishu');
    const res = await groupRoutes.request(
      '/feishu:image-group/generate-image',
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: 'a hedgehog' }),
      },
    );
    expect(res.status).toBe(409);
  });
});

describe('GET /:jid/generated-images', () => {
  beforeEach(() => {
    seedGroup();
    db.ensureChatExists(JID);
  });

  test('lists path-based rows and keeps legacy inline rows renderable', async () => {
    const ts = new Date().toISOString();
    db.storeMessageDirect(
      'gen-path',
      JID,
      '__image_generation__',
      '图像生成',
      '图片已生成。',
      ts,
      true,
      {
        attachments: JSON.stringify([
          {
            type: 'image',
            path: 'generated-images/a.png',
            mimeType: 'image/png',
          },
        ]),
      },
    );
    db.storeMessageDirect(
      'gen-legacy',
      JID,
      '__image_generation__',
      '图像生成',
      '图片已生成。',
      new Date(Date.now() - 1000).toISOString(),
      true,
      {
        attachments: JSON.stringify([
          {
            type: 'image',
            data: TINY_PNG.toString('base64'),
            mimeType: 'image/png',
          },
        ]),
      },
    );

    const res = await groupRoutes.request(`/${JID}/generated-images`);
    expect(res.status).toBe(200);
    const body = (await res.json()) as {
      images: Array<{ path?: string; data?: string }>;
    };
    const paths = body.images.filter((i) => i.path).map((i) => i.path);
    expect(paths).toContain('generated-images/a.png');
    const legacy = body.images.find((i) => i.data);
    expect(legacy?.data).toBe(TINY_PNG.toString('base64'));
  });

  test('hidden for non-owners', async () => {
    process.env.HAPPYCLAW_TEST_USER_ID = 'charlie';
    const res = await groupRoutes.request(`/${JID}/generated-images`);
    expect(res.status).toBe(404);
  });

  test('passes through a well-formed recipe and drops a malformed one', async () => {
    db.storeMessageDirect(
      'gen-recipe',
      JID,
      '__image_generation__',
      '图像生成',
      '图片已生成。',
      new Date().toISOString(),
      true,
      {
        attachments: JSON.stringify([
          {
            type: 'image',
            path: 'generated-images/b.png',
            mimeType: 'image/png',
            recipe: {
              prompt: 'a hedgehog',
              references: [
                {
                  path: 'generated-images/ref-1.png',
                  mimeType: 'image/png',
                  note: 'x',
                },
                { path: 42, mimeType: 'image/png' }, // malformed: dropped
              ],
            },
          },
        ]),
      },
    );
    db.storeMessageDirect(
      'gen-legacy-no-recipe',
      JID,
      '__image_generation__',
      '图像生成',
      '图片已生成。',
      new Date(Date.now() - 1000).toISOString(),
      true,
      {
        attachments: JSON.stringify([
          {
            type: 'image',
            path: 'generated-images/c.png',
            mimeType: 'image/png',
          },
        ]),
      },
    );

    const res = await groupRoutes.request(`/${JID}/generated-images`);
    const body = (await res.json()) as {
      images: Array<{
        path?: string;
        recipe?: {
          prompt: string;
          references?: Array<{ path: string; note?: string }>;
        };
      }>;
    };
    const withRecipe = body.images.find(
      (i) => i.path === 'generated-images/b.png',
    );
    expect(withRecipe?.recipe?.prompt).toBe('a hedgehog');
    expect(withRecipe?.recipe?.references).toHaveLength(1);
    expect(withRecipe?.recipe?.references?.[0].path).toBe(
      'generated-images/ref-1.png',
    );
    const legacy = body.images.find((i) => i.path === 'generated-images/c.png');
    expect(legacy?.recipe).toBeUndefined();
  });

  test('passes through recipe quality/aspectRatio and drops an invalid value', async () => {
    db.storeMessageDirect(
      'gen-recipe-quality',
      JID,
      '__image_generation__',
      '图像生成',
      '图片已生成。',
      new Date().toISOString(),
      true,
      {
        attachments: JSON.stringify([
          {
            type: 'image',
            path: 'generated-images/d.png',
            mimeType: 'image/png',
            recipe: {
              prompt: 'a hedgehog',
              quality: '2k',
              aspectRatio: '16:9',
            },
          },
        ]),
      },
    );
    db.storeMessageDirect(
      'gen-recipe-invalid-quality',
      JID,
      '__image_generation__',
      '图像生成',
      '图片已生成。',
      new Date(Date.now() - 1000).toISOString(),
      true,
      {
        attachments: JSON.stringify([
          {
            type: 'image',
            path: 'generated-images/e.png',
            mimeType: 'image/png',
            recipe: {
              prompt: 'a hedgehog',
              quality: 'ultra',
              aspectRatio: '5:4',
            },
          },
        ]),
      },
    );

    const res = await groupRoutes.request(`/${JID}/generated-images`);
    const body = (await res.json()) as {
      images: Array<{
        path?: string;
        recipe?: { quality?: string; aspectRatio?: string };
      }>;
    };
    const valid = body.images.find((i) => i.path === 'generated-images/d.png');
    expect(valid?.recipe?.quality).toBe('2k');
    expect(valid?.recipe?.aspectRatio).toBe('16:9');
    const invalid = body.images.find(
      (i) => i.path === 'generated-images/e.png',
    );
    expect(invalid?.recipe?.quality).toBeUndefined();
    expect(invalid?.recipe?.aspectRatio).toBeUndefined();
  });
});

describe('DELETE /:jid/generated-images/:messageId', () => {
  beforeEach(() => {
    seedGroup();
    db.getOrCreateDefaultAgentProfile(OWNER_ID);
    db.assignWorkspaceAgentProfile(
      FOLDER,
      db.getOrCreateDefaultAgentProfile(OWNER_ID).id,
    );
    seedImageEnabled();
    generateWorkspaceImage.mockResolvedValue({
      data: TINY_PNG.toString('base64'),
      mimeType: 'image/png',
    });
  });

  async function generateOne(): Promise<{
    messageId: string;
    path: string;
  }> {
    const res = await groupRoutes.request(`/${JID}/generate-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt: 'a hedgehog' }),
    });
    const body = (await res.json()) as {
      messageId: string;
      image: { path: string };
    };
    return { messageId: body.messageId, path: body.image.path };
  }

  test('removes the message row and the backing file', async () => {
    const { messageId, path: imagePath } = await generateOne();
    const absolute = path.join(SHARED_TMP, 'groups', FOLDER, imagePath);
    expect(fs.existsSync(absolute)).toBe(true);

    const res = await groupRoutes.request(
      `/${JID}/generated-images/${messageId}`,
      { method: 'DELETE' },
    );
    expect(res.status).toBe(200);
    expect(fs.existsSync(absolute)).toBe(false);

    const stillThere = db
      .getMessagesPage(JID, undefined, 10)
      .find((m) => m.id === messageId);
    expect(stillThere).toBeUndefined();
  });

  test('also removes the cached low-res thumbnail, if one was generated', async () => {
    // TINY_PNG is just a truncated signature (not a decodable image), so use
    // a real one here — the thumbnail route only caches successfully decoded
    // images.
    const realPng = await sharp({
      create: { width: 400, height: 300, channels: 3, background: 'red' },
    })
      .png()
      .toBuffer();
    generateWorkspaceImage.mockResolvedValueOnce({
      data: realPng.toString('base64'),
      mimeType: 'image/png',
    });
    const { messageId, path: imagePath } = await generateOne();

    const thumbRes = await fileRoutes.request(
      `/${JID}/files/preview/${Buffer.from(imagePath, 'utf-8').toString('base64url')}?thumb=1`,
    );
    expect(thumbRes.status).toBe(200);
    const thumbCacheDir = path.join(SHARED_TMP, 'image-thumbnails', FOLDER);
    expect(fs.readdirSync(thumbCacheDir).length).toBeGreaterThan(0);

    const res = await groupRoutes.request(
      `/${JID}/generated-images/${messageId}`,
      { method: 'DELETE' },
    );
    expect(res.status).toBe(200);
    expect(fs.readdirSync(thumbCacheDir)).toHaveLength(0);
  });

  test('404s for an unknown message id', async () => {
    const res = await groupRoutes.request(
      `/${JID}/generated-images/does-not-exist`,
      { method: 'DELETE' },
    );
    expect(res.status).toBe(404);
  });

  test('cannot be used to delete an unrelated chat message', async () => {
    const ts = new Date().toISOString();
    db.storeMessageDirect(
      'regular-message',
      JID,
      OWNER_ID,
      'Alice',
      'hello',
      ts,
      false,
    );
    const res = await groupRoutes.request(
      `/${JID}/generated-images/regular-message`,
      { method: 'DELETE' },
    );
    expect(res.status).toBe(404);
    const stillThere = db
      .getMessagesPage(JID, undefined, 10)
      .find((m) => m.id === 'regular-message');
    expect(stillThere).toBeDefined();
  });

  test('hidden for non-owners', async () => {
    const { messageId } = await generateOne();
    process.env.HAPPYCLAW_TEST_USER_ID = 'charlie';
    const res = await groupRoutes.request(
      `/${JID}/generated-images/${messageId}`,
      { method: 'DELETE' },
    );
    expect(res.status).toBe(404);
  });
});
