/**
 * Covers the deterministic image generation route contract:
 *
 *   - POST /api/groups/:jid/generate-image persists generated bytes under
 *     generated-images/ in the workspace folder and stores a path-based
 *     attachment (no inline base64) on the message row.
 *   - POST with references forwards them to the service layer.
 *   - GET /api/groups/:jid/generated-images returns the lightweight gallery
 *     listing (path references + legacy inline rows).
 *   - Non-web workspaces and disabled workspaces are rejected.
 */
import fs from 'fs';
import os from 'os';
import path from 'path';

import {
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  test,
  vi,
} from 'vitest';

const SHARED_TMP =
  process.env.HAPPYCLAW_TEST_DATA_DIR ??
  (() => {
    const d = fs.mkdtempSync(
      path.join(os.tmpdir(), 'happyclaw-routes-generate-image-'),
    );
    process.env.HAPPYCLAW_TEST_DATA_DIR = d;
    return d;
  })();

vi.mock('../src/config.js', async (importOriginal) => {
  const real = (await importOriginal()) as Record<string, unknown>;
  const dataDir = process.env.HAPPYCLAW_TEST_DATA_DIR!;
  return {
    ...real,
    DATA_DIR: dataDir,
    GROUPS_DIR: path.join(dataDir, 'groups'),
    STORE_DIR: path.join(dataDir, 'db'),
  };
});

vi.mock('../src/logger.js', () => ({
  logger: { debug: () => {}, info: () => {}, warn: () => {}, error: () => {} },
}));

vi.mock('../src/middleware/auth.ts', () => ({
  authMiddleware: async (c: any, next: any) => {
    c.set('user', {
      id: process.env.HAPPYCLAW_TEST_USER_ID ?? 'alice',
      username: 'alice',
      role: process.env.HAPPYCLAW_TEST_USER_ROLE ?? 'member',
      status: 'active',
      permissions: [],
    });
    return next();
  },
}));

vi.mock('../src/web.js', () => ({
  broadcastNewMessage: () => {},
  invalidateAllowedUserCache: () => {},
}));

const generateWorkspaceImage = vi.fn();
vi.mock('../src/image-generation-service.js', () => ({
  generateWorkspaceImage: (...args: unknown[]) =>
    generateWorkspaceImage(...args),
  ImageGenerationError: class ImageGenerationError extends Error {
    constructor(
      message: string,
      readonly status: 400 | 409 | 502 | 504,
    ) {
      super(message);
    }
  },
}));

const groupRoutesModule = await import('../src/routes/groups.js');
const db = await import('../src/db.js');
const webContext = await import('../src/web-context.js');

const groupRoutes = groupRoutesModule.default;

const OWNER_ID = 'alice';
const JID = 'web:image-group';
const FOLDER = 'image-group';
const TINY_PNG = Buffer.from([
  0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00,
]);

beforeAll(() => {
  fs.mkdirSync(path.join(SHARED_TMP, 'db'), { recursive: true });
  fs.mkdirSync(path.join(SHARED_TMP, 'groups'), { recursive: true });
  db.initDatabase();
  webContext.setWebDeps({
    getRegisteredGroups: () => ({}),
  } as unknown as Parameters<typeof webContext.setWebDeps>[0]);
});

afterEach(() => {
  generateWorkspaceImage.mockReset();
  delete process.env.HAPPYCLAW_TEST_USER_ID;
  delete process.env.HAPPYCLAW_TEST_USER_ROLE;
});

function seedGroup(jid = JID, folder = FOLDER): void {
  db.setRegisteredGroup(jid, {
    name: 'Image Group',
    folder,
    added_at: new Date().toISOString(),
    executionMode: 'container',
    created_by: OWNER_ID,
    conversation_source: 'web',
  } as Parameters<typeof db.setRegisteredGroup>[1]);
}

function seedImageEnabled(): void {
  // Direct binding row so the config exists without the full profile flow.
  db.setWorkspaceImageGenerationConfig(FOLDER, true, 'gpt-image-2');
  const binding = db.getWorkspaceAgentProfileBinding(FOLDER);
  expect(binding).toBeDefined();
}

describe('POST /:jid/generate-image', () => {
  beforeEach(() => {
    seedGroup();
    db.getOrCreateDefaultAgentProfile(OWNER_ID);
    db.assignWorkspaceAgentProfile(
      FOLDER,
      db.getOrCreateDefaultAgentProfile(OWNER_ID).id,
    );
    seedImageEnabled();
    generateWorkspaceImage.mockResolvedValue({
      data: TINY_PNG.toString('base64'),
      mimeType: 'image/png',
    });
  });

  test('persists the image as a workspace file and references it by path', async () => {
    const res = await groupRoutes.request(`/${JID}/generate-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt: 'a hedgehog' }),
    });
    expect(res.status).toBe(200);
    const body = (await res.json()) as { image: { path: string } };
    expect(body.image.path).toMatch(/^generated-images\/generated-.*\.png$/);

    const absolute = path.join(SHARED_TMP, 'groups', FOLDER, body.image.path);
    expect(fs.existsSync(absolute)).toBe(true);
    expect(fs.readFileSync(absolute).subarray(0, 4)).toEqual(
      TINY_PNG.subarray(0, 4),
    );

    // Message attachment references the path — no inline base64 payload.
    const imageRow = db
      .getMessagesPage(JID, undefined, 10)
      .find((m) => m.sender === '__image_generation__');
    expect(imageRow).toBeDefined();
    const attachments = JSON.parse(imageRow!.attachments as string);
    expect(attachments[0].type).toBe('image');
    expect(attachments[0].path).toBe(body.image.path);
    expect(attachments[0].data).toBeUndefined();
  });

  test('forwards references to the service and composes per-image notes into the prompt', async () => {
    const res = await groupRoutes.request(`/${JID}/generate-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt: 'merge the scenes',
        references: [
          {
            data: TINY_PNG.toString('base64'),
            mimeType: 'image/png',
            note: '角色造型',
          },
          { data: TINY_PNG.toString('base64'), mimeType: 'image/png' },
        ],
      }),
    });
    expect(res.status).toBe(200);
    expect(generateWorkspaceImage).toHaveBeenCalledTimes(1);
    const [prompt, model, refs] = generateWorkspaceImage.mock.calls[0];
    expect(prompt).toBe('merge the scenes\n\n参考图 1：角色造型');
    expect(model).toBe('gpt-image-2');
    expect(refs).toHaveLength(2);
    expect(Buffer.from(refs[0].data)).toEqual(TINY_PNG);
    expect(refs[0].mimeType).toBe('image/png');
    expect(refs[1].note).toBeUndefined();
  });

  test('rejects a non-web workspace', async () => {
    seedGroup('feishu:image-group', 'image-group-feishu');
    const res = await groupRoutes.request(
      '/feishu:image-group/generate-image',
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: 'a hedgehog' }),
      },
    );
    expect(res.status).toBe(409);
  });
});

describe('GET /:jid/generated-images', () => {
  beforeEach(() => {
    seedGroup();
    db.ensureChatExists(JID);
  });

  test('lists path-based rows and keeps legacy inline rows renderable', async () => {
    const ts = new Date().toISOString();
    db.storeMessageDirect(
      'gen-path',
      JID,
      '__image_generation__',
      '图像生成',
      '图片已生成。',
      ts,
      true,
      {
        attachments: JSON.stringify([
          {
            type: 'image',
            path: 'generated-images/a.png',
            mimeType: 'image/png',
          },
        ]),
      },
    );
    db.storeMessageDirect(
      'gen-legacy',
      JID,
      '__image_generation__',
      '图像生成',
      '图片已生成。',
      new Date(Date.now() - 1000).toISOString(),
      true,
      {
        attachments: JSON.stringify([
          {
            type: 'image',
            data: TINY_PNG.toString('base64'),
            mimeType: 'image/png',
          },
        ]),
      },
    );

    const res = await groupRoutes.request(`/${JID}/generated-images`);
    expect(res.status).toBe(200);
    const body = (await res.json()) as {
      images: Array<{ path?: string; data?: string }>;
    };
    const paths = body.images.filter((i) => i.path).map((i) => i.path);
    expect(paths).toContain('generated-images/a.png');
    const legacy = body.images.find((i) => i.data);
    expect(legacy?.data).toBe(TINY_PNG.toString('base64'));
  });

  test('hidden for non-owners', async () => {
    process.env.HAPPYCLAW_TEST_USER_ID = 'charlie';
    const res = await groupRoutes.request(`/${JID}/generated-images`);
    expect(res.status).toBe(404);
  });
});
